spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${database}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${username}
    password: ${password}

  jpa:
#    hibernate:
#      ddl-auto: create # or validate, create-drop, none as needed

    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  application:
    name: messaging-stomp

  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  web:
    resources:
      static-locations: classpath:/static,file:profile/

  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          naver:
            client-id: <client-id>
            client-secret: <client-secret>
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - name
              - email
              - username
              - phone

          kakao:
            client-id: <client-id>
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
              - phone_number
              - name
              - profile_nickname

jwt:
  secret: ${JWT_TOKEN}

server:
  address: 0.0.0.0
  port: 8080

#logging:
#  level:
#    root: debug

gemini:
  api-key: ${GEMINI_APIKEY}
  models:
    image: gemini-3-pro-image-preview
    text: gemini-2.5-flash